### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by dreamsxin** [bashrc/libdeep#8]
Ubuntu 16.04
```text
Starting program: /home/develop/workspace/cphalcon7/deps/libdeep/examples/facerec/facerec 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
No of images: 60
0: 15.99731

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7ba5496 in bp_plot_weights () from /usr/local/lib/libdeep.so.0
(gdb) bt
#0  0x00007ffff7ba5496 in bp_plot_weights () from /usr/local/lib/libdeep.so.0
#1  0x0000000000400dc7 in facerec_training ()
#2  0x0000000000401296 in main ()
```

**Comment by bashrc** [comment]
Ok. I'll probably redo the face recognition demo anyhow.
